/**
 * Template Routes
 *
 * Serves agency-agents template library metadata and content.
 * Templates are sourced from data/templates/agency-agents/ (English)
 * and data/templates/agency-agents-zh/ (Chinese), with a pre-built
 * index.json generated by scripts/generate-template-index.ts.
 */

import type { FastifyInstance } from 'fastify';
import { readFile } from 'node:fs/promises';
import { resolve, relative, join } from 'node:path';
import { parse as parseYaml } from 'yaml';

const TEMPLATES_DIR = resolve('./templates');
const INDEX_PATH = join(TEMPLATES_DIR, 'index.json');

// ── Types ───────────────────────────────────────────────────────────

interface TemplateEntry {
  id: string;
  source: 'en' | 'zh';
  name: string;
  description: string;
  division: string;
  filePath: string;
  emoji?: string;
  color?: string;
}

interface TemplateIndex {
  version: number;
  updated: string;
  templates: TemplateEntry[];
}

// ── Index cache ─────────────────────────────────────────────────────

let cachedIndex: TemplateIndex | null = null;
let lastLoad = 0;
const CACHE_TTL_MS = 60_000;

async function loadIndex(): Promise<TemplateIndex> {
  const now = Date.now();
  if (cachedIndex && (now - lastLoad) < CACHE_TTL_MS) {
    return cachedIndex;
  }
  const raw = await readFile(INDEX_PATH, 'utf-8');
  cachedIndex = JSON.parse(raw) as TemplateIndex;
  lastLoad = now;
  return cachedIndex;
}

// ── Helpers ─────────────────────────────────────────────────────────

function parseFrontmatter(content: string): { attrs: Record<string, unknown>; body: string } | null {
  const lines = content.split('\n');
  if (lines[0]?.trim() !== '---') return null;

  let endIndex = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i]?.trim() === '---') { endIndex = i; break; }
  }
  if (endIndex === -1) return null;

  const yamlBlock = lines.slice(1, endIndex).join('\n');
  const body = lines.slice(endIndex + 1).join('\n');
  const parsed = parseYaml(yamlBlock);
  if (typeof parsed !== 'object' || parsed === null) return null;

  const attrs: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(parsed as Record<string, unknown>)) {
    if (value !== null) attrs[key] = value;
  }

  return { attrs, body };
}

function safeResolve(base: string, ...segments: string[]): string {
  return resolve(join(base, ...segments));
}

// ── Routes ──────────────────────────────────────────────────────────

export function registerTemplateRoutes(app: FastifyInstance): void {
  /** List templates with optional filters */
  app.get('/api/templates', async (request, reply) => {
    try {
      const query = request.query as { source?: string; division?: string; search?: string };
      const index = await loadIndex();
      let templates = index.templates;

      if (query.source && ['en', 'zh'].includes(query.source)) {
        templates = templates.filter((t) => t.source === query.source);
      }
      if (query.division) {
        templates = templates.filter((t) => t.division === query.division);
      }
      if (query.search) {
        const q = query.search.toLowerCase();
        templates = templates.filter(
          (t) =>
            t.name.toLowerCase().includes(q) ||
            t.description.toLowerCase().includes(q) ||
            t.division.toLowerCase().includes(q),
        );
      }

      const divisions = [...new Set(templates.map((t) => t.division))].sort();

      return reply.send({
        templates: templates.map((t) => ({
          id: t.id,
          source: t.source,
          name: t.name,
          description: t.description,
          division: t.division,
          filePath: t.filePath,
          ...(t.emoji ? { emoji: t.emoji } : {}),
          ...(t.color ? { color: t.color } : {}),
        })),
        divisions,
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return reply.status(500).send({ error: message });
    }
  });

  /** Get template content (frontmatter-stripped body, ready for system_prompt) */
  app.get('/api/templates/content', async (request, reply) => {
    try {
      const query = request.query as { source?: string; path?: string };

      if (!query.source || !query.path) {
        return reply.status(400).send({ error: 'source and path are required' });
      }
      if (!['en', 'zh'].includes(query.source)) {
        return reply.status(400).send({ error: 'source must be "en" or "zh"' });
      }

      const sourceDir = query.source === 'en' ? 'agency-agents' : 'agency-agents-zh';
      const filePath = join(TEMPLATES_DIR, sourceDir, query.path);
      const resolvedPath = resolve(filePath);
      const allowedBase = resolve(join(TEMPLATES_DIR, sourceDir));

      // Path traversal protection
      if (!resolvedPath.startsWith(allowedBase + '/') && resolvedPath !== allowedBase) {
        return reply.status(403).send({ error: 'Path traversal denied' });
      }

      // Prevent directory listing / accessing non-.md files
      if (!resolvedPath.endsWith('.md')) {
        return reply.status(400).send({ error: 'Only .md files can be read' });
      }

      let raw: string;
      try {
        raw = await readFile(resolvedPath, 'utf-8');
      } catch {
        return reply.status(404).send({ error: 'Template file not found' });
      }

      // Strip BOM
      if (raw.charCodeAt(0) === 0xFEFF) {
        raw = raw.slice(1);
      }

      const parsed = parseFrontmatter(raw);
      if (!parsed) {
        return reply.status(422).send({ error: 'Template has no valid frontmatter' });
      }

      const name = typeof parsed.attrs.name === 'string'
        ? parsed.attrs.name
        : query.path.replace(/\.md$/i, '').replace(/-/g, ' ');
      const description = typeof parsed.attrs.description === 'string'
        ? parsed.attrs.description
        : '';
      const emoji = typeof parsed.attrs.emoji === 'string'
        ? parsed.attrs.emoji
        : undefined;

      return reply.send({
        id: `${query.source}-${query.path.replace(/\.md$/i, '').replace(/\//g, '-')}`,
        name,
        description,
        content: parsed.body.trim(),
        ...(emoji ? { emoji } : {}),
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return reply.status(500).send({ error: message });
    }
  });
}
